server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: pu3-order
  data:
    redis:
      host: ${REDIS_HOST:192.168.137.98}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms

flashsale:
  inventory-url: ${INVENTORY_URL:http://192.168.137.98:8084}
